### PR TITLE
Persian 

### PR DESCRIPTION
**Pull request by ZeeAmini**
[bitcoin_fa.pdf](https://github.com/wbnns/bitcoinwhitepaper/files/3797433/bitcoin_fa.pdf)

### CODE REVIEW

**Comment by khendraw** [comment]
Hello there, thank you for your contribution in translating the Bitcoin whitepaper in Persian Language. Could you kindly provide the source file in .odt (OpenDocument Text) so I can proceed with the merge.

Thanks

**Comment by ZeeAmini** [comment]
Sure! :)
But unfortunately I get the "not supported file type" each time I try to drag the odt form.
Odt doesn't seem to be supported at the moment. Would u pls check it?

**Comment by khendraw** [comment]
Could you please check the file extension and make sure it is bitcoin_fa.odt? It is working fine from my end.

**Comment by ZeeAmini** [comment]
Yes I'm sure about the format. I even downloaded the odt english and tried to upload it here, didn't work! There must be sth wrong with my browser or readers. I'll try to fix it asap and send the file.
Thanks for checking :)

**Comment by wbnns** [comment]
@zeeamini

Thank you for your help. Can you please email the file you made the pdf with, to will@bitcoin.org?

**Comment by ZeeAmini** [comment]
@wbnns  email sent :)🙏

**Pull request closed without merging**
