### PR TITLE
BTC Slovak Translation

### PR DESCRIPTION
**Pull request by OndroS**

### CODE REVIEW

**Comment by khendraw** [comment]
Hi there,
Thank you for your participation in translating the Bitcoin whitepaper to slovak. In order to have this translation merged, we will also need the **.odt** file along with the .pdf file so should there any revisions it can be done without the need to do it from scratch.
Could you kindly please also provide the .odt file?
Thank you.

**Comment by OndroS** [comment]
@khendraw Thank you for your reply. ODT file is pushed in my last commit.

**Comment by khendraw** [comment]
Hi @OndroS, sorry not to tell you this earlier - but we need to retain the document formatting on the whitepaper translation. Just let me know if you have the original format translation or I can do the reformaating for you (using translation already done).  
Thanks

**Comment by OndroS** [comment]
Hi @khendraw, unfortunately, we have whitepaper translation only in this format. If you can do the reformatting I'll be really grateful. Thank you.

**Comment by khendraw** [comment]
Hello,
I've managed to re-formatting to the original whitepaper format. Can you please take a quick look and see if I didn't miss anything.

Sorry it took quite a long time before I can follow up this.

Thanks,

**Pull request merged**
