### PR TITLE
Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rodrigosilvap**

### CODE REVIEW

**Comment by gcunhase** [comment]
Hi, is this translation still ongoing or halted? I'd like to contribute.

**Comment by vpfreitas** [comment]
Hi, Siavann!

I’d started to translate, but for work reasons had not been able to go more than a few paragraphs… please feel free to go on!!

Vinicius Pimentel de Freitas

De: Gwena <notifications@github.com>
Responder a: saivann/bitcoinwhitepaper <reply@reply.github.com>
Fecha: jueves, 21 de septiembre de 2017, 09:21
Para: saivann/bitcoinwhitepaper <bitcoinwhitepaper@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [saivann/bitcoinwhitepaper] Brazilian Portuguese translation (#7)


Hi, is this translation still ongoing or halted? I'd like to contribute.

**Comment by wbnns** [comment]
@gcunhase Hi there! Yes, please feel free to contribute and translate the white paper. Thanks! cc: @vpfreitas

**Comment by gcunhase** [comment]
@vpfreitas cool, would you like to send me what you've already translated so I can build on that?

**Comment by rodrigosilvap** [comment]
I've already translated it all.
But received a message that translation stuff would not be prioritized (or
something like that).

Em 21 de set de 2017 10:52 PM, "Gwena" <notifications@github.com> escreveu:

**Comment by gcunhase** [comment]
Ah okay then, good job nonetheless :) @rodrigosilvap

**Comment by wbnns** [comment]
@rodrigosilvap Awesome! Apologies for the lack of communication; I'm helping take over this - we'll make sure that everything gets incorporated. @gcunhase Thank you also for your interest!

In case either of you are interested, we also need help with the Portuguese translation on Bitcoin.org: https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/assisting-with-translations.md

If you have any questions, please let met know.

**Pull request merged**
